# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Unarine Tshiwawa #Your awesome title
email: unarine.tshiwawa@gmail.com #your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"

  This page will be used to showcase my skills.  I'll keep on posting what
  I've been doing to date.

  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: greatunarine1 #jekyllrb
github_username:  tshuna001 #jekyll

# Build settings
markdown: kramdown
  theme: minima

#plugins_dir:
#  - jekyll-feed

plugins:
  - jekyll-target-blank

#target-blank:
#    rel: nofollow

#header_page_refs: ['now', 'about', 'contact']
